data:extend({
	{
		type = "double-setting",
		name = "entrenched-enemies-base-upgrade-percent",
		setting_type = "startup",
		default_value = 0.2,
		minimum_value = 0.0,
		maximum_value = 1.0,
		order = "aa",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-quality-upgrade-chance-per-chunk",
		setting_type = "startup",
		default_value = 0.01,
		minimum_value = 0.0,
		maximum_value = 0.10,
		order = "ab",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-base-health-multiplier",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 10,
		order = "ac",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-base-regen-multiplier",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 10,
		order = "ad",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-base-spawn-multiplier",
		setting_type = "startup",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 10,
		order = "ae",
	},
})
