data:extend({
	{
		type = "double-setting",
		name = "entrenched-enemies-base-upgrade-percent",
		setting_type = "startup",
		default_value = 0.2,
		minimum_value = 0.0,
		maximum_value = 1.0,
		order = "aa",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-quality-upgrade-chance-per-chunk",
		setting_type = "startup",
		default_value = 0.01,
		minimum_value = 0.0,
		maximum_value = 0.10,
		order = "ab",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-base-health-multiplier",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 10,
		order = "ac",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-base-regen-multiplier",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 10,
		order = "ad",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-base-spawn-multiplier",
		setting_type = "startup",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 10,
		order = "ae",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-demolisher-speed-multiplier",
		setting_type = "startup",
		default_value = 1.4,
		minimum_value = 0.3,
		maximum_value = 3,
		order = "ba",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-demolisher-health-multiplier",
		setting_type = "startup",
		default_value = 3,
		minimum_value = 1,
		maximum_value = 10,
		order = "bb",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-demolisher-regen-multiplier",
		setting_type = "startup",
		default_value = 2,
		minimum_value = 1,
		maximum_value = 10,
		order = "bc",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-demolisher-attack-range-multiplier",
		setting_type = "startup",
		default_value = 1.5,
		minimum_value = 1,
		maximum_value = 3,
		order = "bd",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-demolisher-attack-cooldown-multiplier",
		setting_type = "startup",
		default_value = 0.8,
		minimum_value = 0.1,
		maximum_value = 1,
		order = "be",
	},
	{
		type = "double-setting",
		name = "entrenched-enemies-demolisher-attack-variance-multiplier",
		setting_type = "startup",
		default_value = 0.2,
		minimum_value = 0.0,
		maximum_value = 1,
		order = "be",
	},
})
